// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqXIHWw4o7A30m5svEBjvv30rxO7ju9g0',
    appId: '1:1023543629180:web:b1e559cc350a2e263c40f9',
    messagingSenderId: '1023543629180',
    projectId: 'fir-sample-app-001',
    authDomain: 'fir-sample-app-001.firebaseapp.com',
    storageBucket: 'fir-sample-app-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN0Es3LWzFzS3lbyJeLeU_qNIlhvUf7lc',
    appId: '1:1023543629180:android:0cd886414921cd033c40f9',
    messagingSenderId: '1023543629180',
    projectId: 'fir-sample-app-001',
    storageBucket: 'fir-sample-app-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq4M_wMEica2P05XUW2c-3lWe9AQd2GPk',
    appId: '1:1023543629180:ios:2a93253b0382df753c40f9',
    messagingSenderId: '1023543629180',
    projectId: 'fir-sample-app-001',
    storageBucket: 'fir-sample-app-001.appspot.com',
    iosClientId: '1023543629180-28j39h6drj4l6k96t9neap3sd3hqfkh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq4M_wMEica2P05XUW2c-3lWe9AQd2GPk',
    appId: '1:1023543629180:ios:2a93253b0382df753c40f9',
    messagingSenderId: '1023543629180',
    projectId: 'fir-sample-app-001',
    storageBucket: 'fir-sample-app-001.appspot.com',
    iosClientId: '1023543629180-28j39h6drj4l6k96t9neap3sd3hqfkh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testChatApp',
  );
}
